openapi: 3.1.0
info:
  title: YYC-osk
  description: An application for helping newcomers find their way around Calgary.
  version: "0.1.0"

servers:
  - url: http://localhost:5001
    description: Local host

paths:
  /:
    get:
      summary: Detect server
      description: Detect whether the server is running or not.
      responses:
        "200":
          description: Server is running.
          content:
            text/plain:
              schema:
                type: string

  /dataset{name}:
    parameters:
    - name: name
      in: path
      required: true
      schema:
        type: string
    get:
      summary: Get a dataset
      description:  Get a dataset in CSV format.
      responses:
        "200":
          description: Dataset attached
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataSet"

  /voice:
    post:
      summary: Process a voice command
      description: Audio is sent from the frontend and the converted command is returned.
      requestBody:
        content:
          audio/mpeg: {}
      responses:
        "200":
          description: Audio response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VoiceConversion"
      responses:
        "503":
          description: Conversion service unavailable.
          content:
            application/json:
              schema:
              type: string

components:
  schemas:
    VoiceConversion:
      type: object
      properties:
        language:
          type: string
        user_request:
          type: string
      required:
        - language
        - user_request
    DataSet:
      type: object
      properties:
        data:
          type: array
          description: "Array of data objects"
          items:
            description: "Datum object"
            type: object
      required:
        - data